name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install strongswan
        run: |
          sudo apt update && sudo apt install -y strongswan xl2tpd ppp lsof

      - name: Configure strongswan
        run: |
          echo "Configuring strongswan..."
          sudo bash -c 'cat > /etc/ipsec.conf <<EOF
          config setup
              charondebug="ike 2, knl 2, cfg 2"

          conn L2TP-PSK
              keyexchange=ikev1
              left=%defaultroute
              leftauth=psk
              right=${{ secrets.VPN_GATEWAY }}
              rightauth=psk
              rightsubnet=0.0.0.0/0
              ike=${{ secrets.VPN_IKE }}
              esp=${{ secrets.VPN_ESP }}
              keyingtries=3
              ikelifetime=8h
              lifetime=1h
              dpdaction=clear
              auto=add
          EOF'
          
          sudo bash -c 'cat > /etc/ipsec.secrets <<EOF
          ${{ secrets.VPN_GATEWAY }} : PSK "${{ secrets.VPN_PSK }}"
          EOF'
          
          sudo bash -c 'cat > /etc/xl2tpd/xl2tpd.conf << EOF
          [global]
          ipsec saref = yes

          [lns default]
          ip range = 192.168.1.100-192.168.1.200
          local ip = 192.168.1.1
          require chap = no
          refuse pap = yes
          require authentication = yes
          name = L2TP-Server
          ppp debug = yes
          pppoptfile = /etc/ppp/options.l2tpd
          length bit = yes
          EOF'

          sudo bash -c 'cat > /etc/ppp/options.xl2tpd << EOF
          ipcp-accept-local
          ipcp-accept-remote
          ms-dns 8.8.8.8
          ms-dns 8.8.4.4
          noccp
          auth
          mtu 1410
          mru 1410
          lock
          hide-password
          modem
          name "${{ secrets.VPN_NT_DOMAIN }}\\${{ secrets.VPN_USERNAME }}"
          password "${{ secrets.VPN_PASSWORD }}"
          lcp-echo-interval 30
          lcp-echo-failure 4
          refuse-eap
          refuse-pap
          refuse-chap
          require-mschap-v2
          EOF'

          sudo systemctl restart strongswan-starter xl2tpd
          sudo ipsec restart

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Connect to VPN
        run: |
          echo "Connecting to VPN..."
          sudo ipsec up L2TP-PSK
          echo "c L2TP-PSK" | sudo tee /var/run/xl2tpd/l2tp-control
          sudo ifconfig ppp0 up

      - name: Deploy to Dokku (while connected to VPN)
        run: |
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect VPN
        if: always()
        run: |
          echo "Disconnecting VPN..."
          echo "d L2TP-PSK" | sudo tee /var/run/xl2tpd/l2tp-control
          sudo ipsec down L2TP-PSK