name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y network-manager-l2tp network-manager-l2tp-gnome xl2tpd strongswan

      - name: Configure nm
        run: |
          sudo bash -c 'cat > /etc/ipsec.conf <<EOF
          config setup
              charondebug="ike 2, knl 2, cfg 2"

          conn L2TP-VPN
              keyexchange=ikev1
              type=transport
              authby=secret
              left=%defaultroute
              leftprotoport=17/1701
              right=${{ secrets.VPN_GATEWAY }}
              rightprotoport=17/1701
              ike=${{ secrets.VPN_IKE }}
              esp=${{ secrets.VPN_ESP }}
              dpdaction=clear
              dpddelay=300s
              auto=start
          EOF'

          sudo bash -c 'cat > /etc/ipsec.secrets <<EOF
          : PSK "${{ secrets.VPN_PSK }}"
          EOF'

          sudo bash -c 'cat > /etc/xl2tpd/xl2tpd.conf <<EOF
          [global]
          ipsec saref = yes

          [lns default]
          ip range = 192.168.1.100-192.168.1.200
          local ip = 192.168.1.1
          refuse pap = yes
          require authentication = yes
          ppp debug = yes
          pppoptfile = /etc/ppp/options.l2tpd.client
          length bit = yes
          EOF'

          sudo bash -c 'cat > /etc/ppp/options.l2tpd.client <<EOF
          ipcp-accept-local
          ipcp-accept-remote
          ms-dns 8.8.8.8
          ms-dns 8.8.4.4
          noccp
          auth
          mtu 1400
          mru 1400
          connect-delay 5000
          name "${{ secrets.VPN_USERNAME }}"
          password "${{ secrets.VPN_PASSWORD }}"
          domain "${{ secrets.VPN_NT_DOMAIN }}"
          refuse-eap
          refuse-pap
          refuse-chap
          refuse-mschap
          require-mschap-v2
          EOF'

          sudo systemctl restart strongswan
          sudo systemctl restart xl2tpd

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Connect to VPN
        run: |
          echo "Connecting to VPN..."
          sudo ipsec restart
          sudo ipsec up L2TP-VPN
          echo "c default" | sudo tee /var/run/xl2tpd/l2tp-control
          sudo ip route add default dev ppp0

      - name: Debug VPN connection
        if: always()
        run: |
          ipsec status
          ip a | grep ppp

      - name: Deploy to Dokku (while connected to VPN)
        run: |
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect VPN
        run: |
          echo "Disconnecting VPN..."
          echo "d default" | sudo tee /var/run/xl2tpd/l2tp-control
          sudo ipsec down L2TP-VPN