name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPNC
        run: |
          sudo apt-get update
          sudo apt-get install -y strongswan strongswan-pki libstrongswan-extra-plugins libcharon-extra-plugins


      - name: Configure VPNC
        run: |
          echo "Configuring VPNC..."
          sudo bash -c 'cat > /etc/ipsec.conf <<EOF
          config setup
              charondebug="ike 2, knl 2, cfg 2"

          conn vpn
              keyexchange=ikev2
              auto=start
              ike=${{ secrets.VPN_IKE }}
              esp=${{ secrets.VPN_ESP }}
              leftauth=psk
              rightauth=mschapv2
              right=${{ secrets.VPN_GATEWAY }}
              rightsubnet=0.0.0.0/0
              leftsourceip=%config
              left=%defaultroute
              leftid=${{ secrets.VPN_NT_DOMAIN }}\${{ secrets.VPN_USERNAME }}
              rightid=%any
              dpdaction=restart
              dpddelay=30s
              dpdtimeout=120s
          EOF'
          sudo bash -c 'cat > /etc/ipsec.secrets <<EOF
          ${{ secrets.VPN_NT_DOMAIN }}\${{ secrets.VPN_USERNAME }} : PSK "${{ secrets.VPN_PSK }}"

          # MSCHAPv2 Username and Password
          ${{ secrets.VPN_NT_DOMAIN }}\${{ secrets.VPN_USERNAME }} : XAUTH "${{ secrets.VPN_PASSWORD }}"
          EOF'
          sudo systemctl restart strongswan

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Connect to VPN
        run: |
          echo "Connecting to VPN..."
          sudo ipsec up vpn

      - name: Deploy to Dokku (while connected to VPN)
        run: |
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect VPN
        if: always()
        run: |
          echo "Disconnecting VPN..."
          sudo ipsec down vpn
