name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt-get install -y strongswan xl2tpd net-tools

      - name: Add VPN Connection
        run: |
          sudo bash -c 'cat > /etc/ipsec.conf <<EOF
          conn myvpn
            auto=add
            keyexchange=ikev1
            authby=secret
            type=transport
            left=%defaultroute
            leftprotoport=17/1701
            rightprotoport=17/1701
            right=${{ secrets.VPN_GATEWAY }}
            ike=aes128-sha1-modp1024
            esp=aes128-sha1
          EOF'

          sudo bash -c 'cat > /etc/ipsec.secrets <<EOF
          : PSK "${{ secrets.VPN_PSK }}"
          EOF'

          sudo chmod 600 /etc/ipsec.secrets

          sudo bash -c 'cat > /etc/xl2tpd/xl2tpd.conf <<EOF
          [lac myvpn]
          lns = ${{ secrets.VPN_GATEWAY }}
          ppp debug = yes
          pppoptfile = /etc/ppp/options.l2tpd.client
          length bit = yes
          EOF'

          sudo bash -c 'cat > /etc/ppp/options.l2tpd.client <<EOF
          ipcp-accept-local
          ipcp-accept-remote
          refuse-eap
          require-chap
          noccp
          noauth
          mtu 1280
          mru 1280
          noipdefault
          defaultroute
          usepeerdns
          connect-delay 5000
          domain "${{ secrets.VPN_NT_DOMAIN }}"
          name "${{ secrets.VPN_USERNAME }}"
          password "${{ secrets.VPN_PASSWORD }}"
          EOF'

          sudo chmod 600 /etc/ppp/options.l2tpd.client

      - name: Start VPN Connection
        run: |
          sudo mkdir -p /var/run/xl2tpd
          sudo touch /var/run/xl2tpd/l2tp-control
          service ipsec restart
          service xl2tpd restart

          ipsec up myvpn
          echo "c myvpn" > /var/run/xl2tpd/l2tp-control

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Run tasks after VPN connection
        run: |
          echo "VPN Connected! Now executing required commands..."
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Verify VPN Connection
        if: always()
        run: |
          ifconfig
          ip route

      - name: Disconnect VPN
        if: always()
        run: |
          sudo nmcli connection down my-vpn
