name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y network-manager-l2tp network-manager-l2tp-gnome

      - name: Configure VPN nm connection
        run: |
          sudo bash -c 'cat > /etc/NetworkManager/system-connections/myvpn.nmconnection <<EOF
          [connection]
          id=myvpn
          uuid=eefb6558-af2c-452b-977a-451219161dbb
          type=vpn
          autoconnect=false
          permissions=user:runner:;

          [vpn]
          domain=${{ secrets.VPN_NT_DOMAIN }}
          gateway=${{ secrets.VPN_GATEWAY }}
          ipsec-enabled=yes
          ipsec-esp=${{ secrets.VPN_ESP }}
          ipsec-ike=${{ secrets.VPN_IKE }}
          machine-auth-type=psk
          mru=1400
          mtu=1400
          password-flags=1
          refuse-chap=yes
          refuse-eap=yes
          refuse-mschap=yes
          refuse-pap=yes
          user=${{ secrets.VPN_USERNAME }}
          user-auth-type=${{ secrets.VPN_PASSWORD }}
          service-type=org.freedesktop.NetworkManager.l2tp

          [vpn-secrets]
          ipsec-psk=${{ secrets.VPN_PSK }}

          [ipv4]
          method=auto

          [ipv6]
          addr-gen-mode=stable-privacy
          method=auto

          [proxy]
          EOF'
          sudo chown root:root /etc/NetworkManager/system-connections/myvpn.nmconnection
          sudo chmod 600 /etc/NetworkManager/system-connections/myvpn.nmconnection

      - name: Configure nm
        run: |
          sudo sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf
          sudo bash -c 'cat > /etc/network/interfaces <<EOF
          auto lo
          iface lo inet loopback
          EOF'
          sudo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf

          sudo systemctl stop systemd-networkd.socket systemd-networkd
          sudo systemctl disable systemd-networkd.socket systemd-networkd
          sudo systemctl mask systemd-networkd.socket systemd-networkd

          sudo nmcli device set eth0 managed yes

          sudo nmcli connection add type ethernet ifname eth0 con-name eth0
          sudo nmcli connection up eth0

          sudo systemctl restart NetworkManager

          nmcli general status
          nmcli device status
          nmcli dev show eth0 | grep GENERAL.STATE
          sudo grep -r "unmanaged-devices" /etc/NetworkManager/

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Connect to VPN
        run: |
          echo "Connecting to VPN..."
          nmcli connection up myvpn

      - name: Deploy to Dokku (while connected to VPN)
        run: |
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect VPN
        if: always()
        run: |
          echo "Disconnecting VPN..."
          nmcli connection down myvpn