name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install strongswan
        run: |
          sudo apt-get update
          sudo apt-get install -y strongswan strongswan-pki libstrongswan-extra-plugins libcharon-extra-plugins xl2tpd ppp lsof


      - name: Configure strongswan
        run: |
          echo "Configuring strongswan..."
          sudo bash -c 'cat > /etc/ipsec.conf <<EOF
          config setup
              charondebug="all"
              uniqueids=yes
              strictcrlpolicy=no

          conn vpn
              keyexchange=ike
              auto=start
              left=%defaultroute
              leftprotoport=17/1701
              right=${{ secrets.VPN_GATEWAY }}
              rightprotoport=17/1701
              type=transport
              authby=secret
              ike=${{ secrets.VPN_IKE }}
              esp=${{ secrets.VPN_ESP }}
              keyingtries=3
              ikelifetime=8h
              lifetime=1h
              dpddelay=30
              dpdtimeout=120
              dpdaction=clear
              rekey=no
              leftauth=psk
              rightauth=psk
              rightauth2=xauth-mschapv2

          EOF'
          
          sudo bash -c 'cat > /etc/ipsec.secrets <<EOF
          ${{ secrets.VPN_GATEWAY }} : PSK "${{ secrets.VPN_PSK }}"
          ${{ secrets.VPN_NT_DOMAIN }}\\${{ secrets.VPN_USERNAME }} : XAUTH "${{ secrets.VPN_PASSWORD }}"
          EOF'
          
          sudo bash -c 'cat > /etc/xl2tpd/xl2tpd.conf << EOF
          [global]
          ipsec saref = yes

          [lns default]
          ip range = 10.0.0.10-10.0.0.100
          local ip = 10.0.0.1
          require authentication = yes
          ppp debug = yes
          pppoptfile = /etc/ppp/options.xl2tpd
          length bit = yes
          EOF'

          sudo bash -c 'cat > /etc/ppp/options.xl2tpd << EOF
          ipcp-accept-local
          ipcp-accept-remote
          ms-dns 8.8.8.8
          ms-dns 8.8.4.4
          noccp
          auth
          crtscts
          idle 1800
          mtu 1400
          mru 1400
          connect-delay 5000
          refuse-pap
          refuse-chap
          refuse-mschap
          require-mschap-v2
          name ${{ secrets.VPN_NT_DOMAIN }}\${{ secrets.VPN_USERNAME }}
          password ${{ secrets.VPN_PASSWORD }}
          EOF'

          sudo systemctl restart strongswan-starter xl2tpd
          sudo ipsec restart

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Connect to VPN
        run: |
          echo "Connecting to VPN..."
          sudo ipsec up vpn
          echo "c vpn" | sudo tee /var/run/xl2tpd/l2tp-control

      - name: Deploy to Dokku (while connected to VPN)
        run: |
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect VPN
        if: always()
        run: |
          echo "Disconnecting VPN..."
          sudo ipsec down vpn
