name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt install -y network-manager-l2tp network-manager-l2tp-gnome strongswan xl2tpd

      - name: Setup eth0 interface
        run: |
          sudo sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf
          
          sudo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
          
          sudo systemctl stop systemd-networkd.socket
          sudo systemctl disable systemd-networkd.socket
          sudo systemctl mask systemd-networkd
          sudo systemctl restart NetworkManager
          
          sudo nmcli connection add type ethernet ifname eth0 con-name eth0
          sudo nmcli connection modify eth0 connection.autoconnect yes
          
          sudo nmcli device set eth0 managed yes
          
          sudo nmcli connection up eth0
          
          sudo systemctl restart NetworkManager

      - name: Add VPN Connection
        run: |
          sudo nmcli connection add type vpn \
            ifname '' \
            con-name my-vpn \
            autoconnect no \
            vpn-type l2tp \
            vpn.user-name "${{ secrets.VPN_USERNAME }}" \
            vpn.data "gateway=${{ secrets.VPN_GATEWAY }},ipsec-enabled=yes,ipsec-psk=${{ secrets.VPN_PSK }},password-flags=0,domain=${{ secrets.VPN_NT_DOMAIN }},ike=3des-sha1-modp1024,esp=3des-sha1" \
            vpn.secrets "password=${{ secrets.VPN_PASSWORD }}"

            sudo systemctl restart NetworkManager

      - name: Start VPN Connection
        run: |
          sudo nmcli connection up my-vpn

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Run tasks after VPN connection
        run: |
          echo "VPN Connected! Now executing required commands..."
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Verify VPN Connection
        if: always()
        run: |
          journalctl -xeu NetworkManager | tail -n 50
          nmcli connection show my-vpn | grep -E 'ike|esp'
          sudo ipsec listalgs

      - name: Disconnect VPN
        if: always()
        run: |
          sudo nmcli connection down my-vpn
