name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPNC
        run: |
          sudo apt-get update
          sudo apt-get install -y vpnc

      - name: Configure VPNC
        run: |
          echo "Configuring VPNC..."
          sudo bash -c 'cat > /etc/vpnc/default.conf <<EOF
          IPSec gateway ${{ secrets.VPN_GATEWAY }}
          IPSec ID ${{ secrets.VPN_GROUP_ID }}
          IPSec secret ${{ secrets.VPN_GROUP_SECRET }}
          Xauth username ${{ secrets.VPN_USERNAME }}
          Xauth password ${{ secrets.VPN_PASSWORD }}
          EOF'
          sudo chmod 600 /etc/vpnc/default.conf

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          sudo bash -c 'cat > ~/.ssh/id_rsa <<EOF
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF'
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts

      - name: Connect to VPN
        run: |
          echo "Connecting to VPN..."
          sudo vpnc default --background

      - name: Deploy to Dokku (while connected to VPN)
        run: |
          git remote add dokku ${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect VPN
        if: always()
        run: |
          echo "Disconnecting VPN..."
          sudo vpnc-disconnect || echo "VPN already disconnected."
