name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPN dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y strongswan xl2tpd ppp

      - name: Configure IPsec
        run: |
          cat <<EOF | sudo tee /etc/ipsec.conf
          config setup
              uniqueids=no
              charondebug="all"

          conn L2TP-PSK
              keyexchange=ikev1
              dpdaction=clear
              dpddelay=30
              rekey=no
              left=%any
              leftprotoport=17/1701
              right=${{ secrets.VPN_GATEWAY }}
              rightprotoport=17/1701
              rightsubnet=0.0.0.0/0
              auto=add
              ike=${{ secrets.VPN_IKE }}
              esp=${{ secrets.VPN_ESP }}
              authby=secret
          EOF

      - name: Set up IPsec secrets
        run: |
          echo "${{ secrets.VPN_GATEWAY }} : PSK \"${{ secrets.VPN_PSK }}\"" | sudo tee /etc/ipsec.secrets

      - name: Restart IPsec and establish tunnel
        run: |
          sudo systemctl restart strongswan-starter
          sudo ipsec restart
          sudo ipsec up L2TP-PSK

      - name: Configure L2TP tunnel
        run: |
          cat <<EOF | sudo tee /etc/xl2tpd/xl2tpd.conf
          [global]
          ipsec saref = yes
          listen-addr = ${{ secrets.VPN_GATEWAY }}

          [lns default]
          ip range = 192.168.1.100-192.168.1.200
          local ip = 192.168.1.1
          refuse pap = yes
          require authentication = yes
          ppp debug = yes
          pppoptfile = /etc/ppp/options.l2tpd
          length bit = yes
          EOF

      - name: Configure PPP options
        run: |
          cat <<EOF | sudo tee /etc/ppp/options.l2tpd
          require-mschap-v2
          refuse-pap
          refuse-chap
          refuse-mschap
          ms-dns 8.8.8.8
          ms-dns 8.8.4.4
          auth
          mtu 1400
          mru 1400
          crtscts
          lock
          hide-password
          local
          noipdefault
          proxyarp
          connect-delay 5000
          name ${{ secrets.VPN_USERNAME }}
          domain ${{ secrets.VPN_NT_DOMAIN }}
          password ${{ secrets.VPN_PASSWORD }}
          EOF

      - name: Restart L2TP and connect
        run: |
          sudo systemctl restart xl2tpd
          sleep 5
          echo "c L2TP-PSK" | sudo tee /var/run/xl2tpd/l2tp-control

      - name: Verify VPN connection
        run: |
          ip a
          ip route

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Run tasks after VPN connection
        run: |
          echo "VPN Connected! Now executing required commands..."
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect from VPN
        run: |
          echo "d L2TP-PSK" | sudo tee /var/run/xl2tpd/l2tp-control
          sudo ipsec down L2TP-PSK