name: Connect to VPN and Deploy

on:
  push:
    branches:
      - prod

jobs:
  vpn-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPN dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install strongswan xl2tpd

      - name: Configure IPsec
        run: |
          cat <<EOF | sudo tee /etc/ipsec.conf
          config setup

          conn %default
              ikelifetime=60m
              keylife=20m
              rekeymargin=3m
              keyingtries=1
              keyexchange=ikev1
              authby=secret
              ike=aes128-sha1-modp1024,3des-sha1-modp1024!
              esp=aes128-sha1-modp1024,3des-sha1-modp1024!

          conn L2TP-PSK
              keyexchange=ikev1
              left=%defaultroute
              auto=add
              authby=secret
              type=transport
              leftprotoport=17/1701
              rightprotoport=17/1701
              right=${{ secrets.VPN_GATEWAY }}
          EOF

      - name: Set up IPsec secrets
        run: |
          echo ": PSK \"${{ secrets.VPN_PSK }}\"" | sudo tee /etc/ipsec.secrets

      - name: Restart IPsec and establish tunnel
        run: |
          sudo systemctl restart strongswan-starter
          sudo ipsec restart
          sudo ipsec up L2TP-PSK

      - name: Configure L2TP tunnel
        run: |
          cat <<EOF | sudo tee /etc/xl2tpd/xl2tpd.conf
          [global]
          ipsec saref = yes
          listen-addr = ${{ secrets.VPN_GATEWAY }}

          [lns default]
          ip range = 192.168.1.100-192.168.1.200
          local ip = 192.168.1.1
          refuse pap = yes
          require authentication = yes
          ppp debug = yes
          pppoptfile = /etc/ppp/options.l2tpd
          length bit = yes
          EOF

      - name: Configure PPP options
        run: |
          cat <<EOF | sudo tee /etc/ppp/options.l2tpd
          ipcp-accept-local
          ipcp-accept-remote
          refuse-eap
          require-mschap-v2
          noccp
          noauth
          logfile /var/log/xl2tpd.log
          idle 1800
          mtu 1410
          mru 1410
          defaultroute
          usepeerdns
          debug
          connect-delay 5000
          name ${{ secrets.VPN_USERNAME }}
          domain ${{ secrets.VPN_NT_DOMAIN }}
          password ${{ secrets.VPN_PASSWORD }}
          EOF

      - name: Restart L2TP and connect
        run: |
          sudo mkdir -p /var/run/xl2tpd
          sudo touch /var/run/xl2tpd/l2tp-control
          sudo service strongswan restart
          sudo service xl2tpd restart
          sudo service ipsec restart
          sleep 8
          sudo ipsec up L2TP-PSK
          sleep 8
          sudo bash -c 'echo "c myVPN" > /var/run/xl2tpd/l2tp-control'
          sleep 8
          ifconfig

      - name: Verify VPN connection
        if: always()
        run: |
          sudo journalctl -u strongswan-starter --no-pager --lines=50
          sudo ipsec statusall
          sudo ipsec verify

      - name: Setup SSH Key for Dokku
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Run tasks after VPN connection
        run: |
          echo "VPN Connected! Now executing required commands..."
          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
          git push dokku prod:master

      - name: Disconnect from VPN
        run: |
          sudo bash -c 'echo "d myVPN" > /var/run/xl2tpd/l2tp-control'
          ipsec down L2TP-PSK